import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import "./GitHubConnect.css";

async function responseData(response) {
  const text = await response.text();
  try { return text ? JSON.parse(text) : {}; } catch { return { error: `The GitHub service returned an unexpected response (${response.status}).` }; }
}

function GitHubConnect({ projectName, htmlCode = "", cssCode = "", jsCode = "" }) {
  const [loading, setLoading] = useState(false); const [connected, setConnected] = useState(false);
  const [connection, setConnection] = useState(null); const [repositories, setRepositories] = useState([]);
  const [selectedRepo, setSelectedRepo] = useState(null); const [branches, setBranches] = useState([]); const [branch, setBranch] = useState("");
  const [repoName, setRepoName] = useState(""); const [repoDescription, setRepoDescription] = useState(""); const [repoPrivate, setRepoPrivate] = useState(false);
  const [commitMessage, setCommitMessage] = useState("Export website from AI Website Builder"); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const token = async () => { const { data, error: sessionError } = await supabase.auth.getSession(); if (sessionError) throw sessionError; if (!data.session?.access_token) throw new Error("Please log in first."); return data.session.access_token; };
  const request = async (url, options = {}) => { const accessToken = await token(); const response = await fetch(url, { ...options, headers: { Authorization: `Bearer ${accessToken}`, ...(options.body ? { "Content-Type": "application/json" } : {}), ...options.headers } }); const data = await responseData(response); if (!response.ok) throw new Error(data.error || "GitHub request failed."); return data; };
  const loadRepos = async () => { setLoading(true); try { const data = await request("/api/github/repos"); setRepositories(data.repositories || []); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const loadStatus = async () => { try { const data = await request("/api/github/status"); setConnected(Boolean(data.connected)); setConnection(data.connection || null); if (data.connected) await loadRepos(); } catch (err) { setError(err.message); } };
  useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.get("github_error")) setError(params.get("github_error")); if (params.has("github_connected") || params.has("github_error")) window.history.replaceState({}, "", window.location.pathname); loadStatus(); }, []);
  const connect = async () => { setLoading(true); setError(""); try { const data = await request("/api/github/connect", { method: "POST", body: JSON.stringify({ returnTo: window.location.pathname }) }); window.location.assign(data.authorizationUrl); } catch (err) { setError(err.message); setLoading(false); } };
  const selectRepo = async (repo) => { setSelectedRepo(repo); setBranches([]); setBranch(""); setError(""); setLoading(true); try { const data = await request(`/api/github/branches?owner=${encodeURIComponent(repo.owner)}&repo=${encodeURIComponent(repo.name)}`); setBranches(data.branches || []); setBranch(data.defaultBranch || data.branches?.[0]?.name || ""); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const createRepo = async (event) => { event.preventDefault(); setLoading(true); setError(""); try { const data = await request("/api/github/create-repo", { method: "POST", body: JSON.stringify({ name: repoName, description: repoDescription, private: repoPrivate }) }); setRepoName(""); setRepoDescription(""); setRepoPrivate(false); await loadRepos(); await selectRepo({ ...data.repository, owner: data.repository.full_name.split("/")[0] }); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const push = async () => { if (!selectedRepo || !branch) return; setLoading(true); setError(""); try { const title = projectName || "My Website"; const index = `<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${title}</title><link rel="stylesheet" href="style.css"></head><body>\n${htmlCode}\n<script src="script.js"></script></body></html>\n`; const data = await request("/api/github/push", { method: "POST", body: JSON.stringify({ owner: selectedRepo.owner, repo: selectedRepo.name, branch, message: commitMessage, files: [{ path: "index.html", content: index }, { path: "style.css", content: cssCode }, { path: "script.js", content: jsCode }] }) }); setSuccess(data.repositoryUrl); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const disconnect = async () => { if (!window.confirm("Disconnect GitHub?")) return; setLoading(true); try { await request("/api/github/disconnect", { method: "POST" }); setConnected(false); setConnection(null); setRepositories([]); setSelectedRepo(null); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  if (!connected) return <div className="github-connect github-connect-only"><button type="button" className="github-connect-button" onClick={connect} disabled={loading}>{loading ? "Connecting..." : "Connect GitHub"}</button>{error && <div className="github-error">{error}</div>}</div>;
  return <div className="github-connect"><div className="github-connection-row"><div className="github-connected">✓ GitHub Connected {connection?.login && `— ${connection.login}`}</div><button type="button" className="github-refresh-button" onClick={disconnect} disabled={loading}>Disconnect</button></div><form onSubmit={createRepo} className="github-card"><div className="github-card-title">Create New Repository</div><input className="github-input" placeholder="Repository name" value={repoName} onChange={(e) => setRepoName(e.target.value)} required/><textarea className="github-textarea" placeholder="Description (optional)" value={repoDescription} onChange={(e) => setRepoDescription(e.target.value)}/><label className="github-checkbox"><input type="checkbox" checked={repoPrivate} onChange={(e) => setRepoPrivate(e.target.checked)}/>Private repository</label><button className="github-create-button" disabled={loading}>{loading ? "Creating..." : "Create Repository"}</button></form><div className="github-card"><div className="github-repo-header"><div className="github-card-title">Select Repository</div><button type="button" className="github-refresh-button" onClick={loadRepos} disabled={loading}>Refresh</button></div>{repositories.length ? <div className="github-repo-list">{repositories.map((repo) => <button type="button" key={repo.id} className={`github-repo ${selectedRepo?.id === repo.id ? "github-repo-selected" : ""}`} onClick={() => selectRepo(repo)}><span><strong>{repo.name}</strong><span className="github-repo-meta">{repo.private ? "Private" : "Public"} · {repo.default_branch}</span></span></button>)}</div> : <p className="github-muted">{loading ? "Loading repositories..." : "No repositories found."}</p>}</div>{selectedRepo && <div className="github-card"><div className="github-card-title">Push website to {selectedRepo.name}</div><label className="github-label">Branch</label><select className="github-input" value={branch} onChange={(e) => setBranch(e.target.value)} disabled={loading || !branches.length}>{branches.map((item) => <option key={item.name} value={item.name}>{item.name}{item.default ? " (default)" : ""}</option>)}</select><input className="github-input" value={commitMessage} onChange={(e) => setCommitMessage(e.target.value)} placeholder="Commit message"/><button type="button" className="github-create-button" onClick={push} disabled={loading || !branch}>{loading ? "Pushing..." : "Push to GitHub"}</button></div>}{error && <div className="github-error">{error}</div>}{success && <div className="github-success">Website files pushed successfully. <a href={success} target="_blank" rel="noreferrer">Open repository</a></div>}</div>;
}
export default GitHubConnect;
